#!/bin/sh
mkdir -p /home/bvodola/webapps/zeni_app/run
pid=$(/sbin/pidof /home/bvodola/webapps/zeni_app/bin/node)
if echo "$pid" | grep -q " "; then
  pid=""
fi
if [ -n "$pid" ]; then
  user=$(ps -p $pid -o user:20 | tail -n 1)
  if [ $user = "bvodola" ]; then
    exit 0
  fi
fi
nohup /home/bvodola/webapps/zeni_app/bin/node /home/bvodola/webapps/zeni_app/bundle/main.js > /dev/null 2>&1 &
/sbin/pidof /home/bvodola/webapps/zeni_app/bin/node > /home/bvodola/webapps/zeni_app/run/node.pid
